# Build variables

#OBJ = src/*.c
#INC = inc/*.h

APP_NAME = ball_path
MAIN = main.c

CC = gcc
OPT = -std=c99

# Build target
all:
	@echo "Building ball_path application"
	@$(CC) $(OPT) -o $(APP_NAME) $(MAIN)

clean:
	@echo "Cleaning ball_path application"
	@rm -rf $(APP_NAME)

